version: '2'
services:
   php:
      build: .
      ports:
        - "8002:80"
      environment:
         CSSCOMPILER: "SASS"
      volumes:
        - .:/var/www/html
      entrypoint: "/entrypoint.sh"
      command: "apache2-foreground"
